# Generated by Django 6.0.7 on 2026-07-12 09:58

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Enable the pgvector extension before any VectorField table is created.
        # Runs automatically on migrate (including on Render, which has no shell).
        VectorExtension(),
        migrations.CreateModel(
            name='IngestedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('chunk_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('ordinal', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
            ],
            options={
                'ordering': ['source', 'ordinal'],
                'indexes': [models.Index(fields=['source'], name='rag_documen_source_eeefd4_idx')],
            },
        ),
    ]
