# Generated by Django 6.0.7 on 2026-07-12 17:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='rag_documen_search__0a0cea_gin'),
        ),
    ]
