# Generated by Django 6.0.7 on 2026-07-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('node_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('level', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('path', models.CharField(max_length=600)),
                ('position', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vectorless.documentnode')),
            ],
            options={
                'ordering': ['source', 'position'],
                'indexes': [models.Index(fields=['source'], name='vectorless__source_8bbe24_idx'), models.Index(fields=['parent'], name='vectorless__parent__2fd0b9_idx')],
            },
        ),
    ]
