# Generated by Django 6.0.7 on 2026-07-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GraphSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('triple_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, max_length=300)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='kg.entity')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='kg.entity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'predicate', 'object', 'source'), name='unique_relationship_per_source')],
            },
        ),
    ]
