# Generated by Django 6.0.7 on 2026-07-14 06:50

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0001_initial'),
    ]

    operations = [
        # Ensure the pgvector extension exists before adding a vector column. Idempotent
        # (CREATE EXTENSION IF NOT EXISTS); needed because app migration order in a fresh
        # database (e.g. the test DB) is not guaranteed relative to the rag app.
        VectorExtension(),
        migrations.AddField(
            model_name='relationship',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072, null=True),
        ),
    ]
