# Generated by Django 6.0.7 on 2026-07-18 09:24

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Enable pgvector before creating a vector column (idempotent; needed for a fresh
        # test DB where app migration order relative to rag/kg is not guaranteed).
        VectorExtension(),
        migrations.CreateModel(
            name='MultimodalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('chunk_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultimodalChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('kind', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('image', 'image')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('context', models.CharField(blank=True, max_length=600)),
                ('image_b64', models.TextField(blank=True)),
                ('figure_key', models.CharField(blank=True, max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
            ],
            options={
                'ordering': ['source', 'page', 'id'],
                'indexes': [models.Index(fields=['source'], name='multimodal__source_2265c1_idx')],
            },
        ),
    ]
